[package]
name = "jelly"
version = "0.1.0"
edition = "2021"
author= "Diego Cortes"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.5"
reqwest = {version = "0.11", features = ["json"]}
tokio = { version = "1", features = ["full"] }
serde = { version= "1.0.210", features = ["derive"]}
quick-xml = { version ="0.36.1", features = ["serialize"]}
async-trait = "0.1.82"
regex = "1.11.0"
thiserror = "1.0"
clap = { version = "4.0", features = ["derive"] }
crossterm = "0.27"
